- name: Harden web and db containers
  hosts: all
  tasks:
    - name: Ensure ufw is installed
      apt:
        name: ufw
        state: present
    - name: Enable ufw
      command: ufw enable
      ignore_errors: yes
